### PR TITLE
feat: add `mock` function to overrides non-configurable props

### LINKED ISSUE #99: `window.document` cannot be mocked / replaced
I tried something like this:

```ts
  hooks.beforeEach(function() {
    this.pageVisibility = this.owner.lookup('service:page-visibility');

    const VISIBILITY_STATE = Symbol('visibility state');

    class DocumentMock extends EventTarget {
      [VISIBILITY_STATE] = 'visible';

      get visibilityState() {
        return this[VISIBILITY_STATE];
      }

      get hidden() {
        return this.visibilityState !== 'visible';
      }
    }

    window.document = new DocumentMock();

    this.triggerVisibilityChange = visibilityState => {
      if (window.document[VISIBILITY_STATE] === visibilityState) return;
      window.document[VISIBILITY_STATE] = visibilityState;
      this.dispatchEvent(new Event('visibilitychange'));
    };
  });
```

But this throws the following error:

```
TypeError: 'set' on proxy: trap returned truish for property 'document'
  which exists in the proxy target as a non-configurable and non-writable
  accessor property without a setter
```

The reason being

> Take a look at the following, section 9.5.9 of the ECMA spec:
>
> http://www.ecma-international.org/ecma-262/6.0/#sec-proxy-object-internal-methods-and-internal-slots-set-p-v-receiver
>
> A riveting read I'm sure you'll agree.
>
> I believe the two keys lines are:
>
>> Let booleanTrapResult be ToBoolean(Call(trap, handler, «target, P, V, Receiver»)).
>
> and the equally esoteric:
>
>> If targetDesc is not undefined, then
>> a. If IsDataDescriptor(targetDesc) and targetDesc.[[Configurable]] is false and targetDesc.[[Writable]] is false, then
>>
>> i. If SameValue(V, targetDesc.[[Value]]) is false, throw a TypeError exception.
>
> There is this relevant comment in the NOTE section:
>
>> Cannot change the value of a property to be different from the value of the corresponding target object property if the corresponding target object property is a non-writable, non-configurable own data property.

— [StackOverflow](https://stackoverflow.com/a/46273767)

With the current setup, it is not possible to completely mock properties like `document`.

Can we maybe add a method / export a function to directly set properties on the `holder`? This way we could do something like:

```ts
import window, { mock } from 'ember-window-mock';

module('foo', function(hooks) {
  hooks.beforeEach(function() {
    class DocumentMock extends EventTarget {
      // ...
    }

    mock('document', new DocumentMock());
  });
});

### PR DESCRIPTION
**Pull request by buschtoens**
Based on #100. Fixes #99.

I don't know, if `mock` is the best name. Maybe `override`? I don't know. 🤷‍♀️ 😄

### CODE REVIEW

**Comment by VincentMolinie** [comment]
Can someone review this 🙏  ?

**Comment by boydkr** [comment]
I could very much use this PR.  I'm stuck on 0.6.0 until there's some way to mock `onbeforeunload`

**Comment by AndreJoaquim** [comment]
Hey @simonihmig! I know you probably have more important things to do 😅 But is there any chance we could get this PR merged? It'd be very helpful 🙏🏻 Thanks in advance for all your work!

**Comment by simonihmig** [comment]
Hey folks, so the thing here is that this is based (contains those commits) on #100, which had some longer discussions a (even longer) while ago, and which seems to not have been finalized. 

I am really not aware anymore of the exact state of those PRs, would need some time to dig into it again. AFAIR the work in #100 is technically required before we can land this, right?

@buschtoens what about you, are you still interested in working on these? Somehow the momentum was interrupted at some point unfortunately, and the PRs became dormant. Not intending to blame anyone here, not having the time to continue work would be totally understandable, just want to figure out if/how we can move this forward!

**Comment by simonihmig** [comment]
> I'm stuck on 0.6.0 until there's some way to mock onbeforeunload

Sorry @boydkr for the late reply. Could you explain why you need this PR to mock `onbeforeunload`. It is a writeable prop after all, right? So that *should* work, unless I am missing something. In case there is an issue, but it is unrelated to this PR here - which is about overriding non-configurable, non-writable properties AFAIU - then please file a separate issue!

**Comment by simonihmig** [comment]
Closing this as the work is abandoned and way out of sync.

**Pull request closed without merging**
